import fs from 'fs';
import path from 'path';
import { JOBS_BASE_DIR } from '../../config';
import type { JobEntity } from '../../domain/Job';

/**
 * Sequentially merges all children's generated output into a single
 * `final-project/` directory.  On filename collision, renames duplicates
 * by inserting the childId prefix so nothing is silently overwritten.
 *
 * After merging, scaffolds a runnable Playwright project:
 *   - package.json
 *   - playwright.config.ts (with screenshot/trace/video settings from job)
 *   - README.md
 */
export class ProjectMerger {
  merge(job: JobEntity, childIds: string[]): string {
    const finalDir = path.join(JOBS_BASE_DIR, job.jobId, 'final-project');
    fs.mkdirSync(finalDir, { recursive: true });

    for (const childId of childIds) {
      const srcDir = path.join(JOBS_BASE_DIR, job.jobId, 'children', childId, 'generated');
      if (!fs.existsSync(srcDir)) continue;
      this.copyDir(srcDir, finalDir, childId);
    }

    this.scaffoldProject(finalDir, job);

    return finalDir;
  }

  private copyDir(src: string, dest: string, childId: string): void {
    for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
      const srcPath = path.join(src, entry.name);
      if (entry.isDirectory()) {
        const subDest = path.join(dest, entry.name);
        fs.mkdirSync(subDest, { recursive: true });
        this.copyDir(srcPath, subDest, childId);
      } else {
        let destPath = path.join(dest, entry.name);
        if (fs.existsSync(destPath)) {
          const ext = path.extname(entry.name);
          const base = path.basename(entry.name, ext);
          destPath = path.join(dest, `${base}.${childId}${ext}`);
        }
        fs.copyFileSync(srcPath, destPath);
      }
    }
  }

  private scaffoldProject(finalDir: string, job: JobEntity): void {
    // ── package.json ─────────────────────────────────────────────────────────
    const pkgJson = {
      name: 'generated-playwright-project',
      version: '1.0.0',
      private: true,
      scripts: {
        test: 'npx playwright test',
        'test:headed': 'npx playwright test --headed',
        'show-report': 'npx playwright show-report',
      },
      devDependencies: {
        '@playwright/test': '^1.41.0',
        typescript: '^5.3.3',
      },
    };
    fs.writeFileSync(
      path.join(finalDir, 'package.json'),
      JSON.stringify(pkgJson, null, 2),
      'utf8',
    );

    // ── playwright.config.ts ──────────────────────────────────────────────────
    const screenshot = job.screenshotOnFailure ? "'only-on-failure'" : "'off'";
    const trace = job.traceOnFailure ? "'retain-on-failure'" : "'off'";
    const video = job.videoOnFailure ? "'retain-on-failure'" : "'off'";

    const playwrightConfig = `import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  fullyParallel: false,
  forbidOnly: !!process.env['CI'],
  retries: ${job.retryCount},
  workers: 1,
  reporter: [['html', { open: 'never' }], ['line']],
  use: {
    headless: ${job.headless},
    screenshot: ${screenshot},
    trace: ${trace},
    video: ${video},
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
});
`;
    fs.writeFileSync(path.join(finalDir, 'playwright.config.ts'), playwrightConfig, 'utf8');

    // ── tsconfig.json ─────────────────────────────────────────────────────────
    const tsConfig = {
      compilerOptions: {
        target: 'ES2022',
        module: 'CommonJS',
        moduleResolution: 'node',
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
      },
    };
    fs.writeFileSync(
      path.join(finalDir, 'tsconfig.json'),
      JSON.stringify(tsConfig, null, 2),
      'utf8',
    );

    // ── README.md ─────────────────────────────────────────────────────────────
    const readme = `# Generated Playwright Project

Auto-generated by the AI QA Automation Platform.

## Setup

\`\`\`bash
npm install
npx playwright install
\`\`\`

## Run Tests

\`\`\`bash
npm test
\`\`\`

## View Report

\`\`\`bash
npm run show-report
\`\`\`

## Project Structure

\`\`\`
.
├── pages/          # Page Object Models
├── tests/          # Playwright spec files
├── locators/       # Resolved locator snapshots
├── reports/        # Execution reports
├── playwright.config.ts
└── package.json
\`\`\`
`;
    fs.writeFileSync(path.join(finalDir, 'README.md'), readme, 'utf8');

    // ── ensure required subdirs exist ─────────────────────────────────────────
    for (const dir of ['pages', 'tests', 'locators', 'test-data', 'reports']) {
      fs.mkdirSync(path.join(finalDir, dir), { recursive: true });
    }
  }
}
