import { test, expect } from "@playwright/test";

/**
 * Authentication tests — generated by AI Automation Framework
 * Source test-case IDs: tc-001, tc-002
 */

test.describe("Authentication", () => {
  test("tc-001 — User can log in with valid credentials", async ({ page }) => {
    await page.goto("/login");

    await page.locator("[data-testid='email-input']").fill("test@example.com");
    await page.locator("[data-testid='password-input']").fill("correct-horse-battery-staple");
    await page.locator("[data-testid='login-button']").click();

    await expect(page).toHaveURL(/.*\/dashboard/);
    await expect(page.locator("[data-testid='welcome-banner']")).toBeVisible();
  });

  test("tc-002 — Login fails with invalid password and shows error message", async ({ page }) => {
    await page.goto("/login");

    await page.locator("[data-testid='email-input']").fill("test@example.com");
    await page.locator("[data-testid='password-input']").fill("wrong-password");
    await page.locator("[data-testid='login-button']").click();

    await expect(page.locator("[data-testid='error-message']")).toBeVisible();
    await expect(page.locator("[data-testid='error-message']")).toHaveText(
      "Invalid email or password"
    );
    await expect(page).toHaveURL(/.*\/login/);
  });
});
