import { test, expect } from "@playwright/test";

/**
 * Cart tests — generated by AI Automation Framework
 * Source test-case IDs: tc-003
 */

test.describe("Shopping Cart", () => {
  test("tc-003 — User can add a product to the shopping cart", async ({ page }) => {
    await page.goto("/products");

    await page.locator("[data-testid='product-card']:first-child").click();
    await page.locator("[data-testid='add-to-cart-button']").click();

    await expect(page.locator("[data-testid='cart-count-badge']")).toHaveText("1");
    await expect(page.locator("[data-testid='cart-success-toast']")).toBeVisible();
  });
});
