import { test, expect } from "@playwright/test";

/**
 * Contact form tests — generated by AI Automation Framework
 * Source test-case IDs: tc-005
 */

test.describe("Contact Form", () => {
  test("tc-005 — Contact form submits successfully", async ({ page }) => {
    await page.goto("/contact");

    await page.locator("[data-testid='contact-name']").fill("Jane Smith");
    await page.locator("[data-testid='contact-email']").fill("jane@example.com");
    await page
      .locator("[data-testid='contact-message']")
      .fill("Hello, I am interested in your enterprise plan.");
    await page.locator("[data-testid='contact-submit-button']").click();

    await expect(
      page.locator("[data-testid='submission-success-message']")
    ).toBeVisible();
    await expect(
      page.locator("[data-testid='submission-success-message']")
    ).toHaveText("Thank you! We'll be in touch soon.");
  });
});
