import { test, expect } from "@playwright/test";

/**
 * Search tests — generated by AI Automation Framework
 * Source test-case IDs: tc-004
 */

test.describe("Search", () => {
  test("tc-004 — Search returns relevant results", async ({ page }) => {
    await page.goto("/search");

    await page.locator("[data-testid='search-input']").fill("laptop");
    await page.keyboard.press("Enter");

    await expect(page.locator("[data-testid='search-result-item']")).toHaveCount(
      await page.locator("[data-testid='search-result-item']").count()
    );
    expect(
      await page.locator("[data-testid='search-result-item']").count()
    ).toBeGreaterThan(0);
    await expect(page.locator("[data-testid='results-heading']")).toHaveText(
      'Results for "laptop"'
    );
  });
});
